package uk.ac.susx.tag.lucenesearch.query_expansion.spellcheck;


import java.util.List;

/*
Wraps up a suggestion generated by Lucene's SpellChecker
 */
public class Suggestion {

    private String originalTerm;
    private List<String> suggestions;

    public Suggestion(String originalTerm, List<String> suggestions) {
        this.originalTerm = originalTerm;
        this.suggestions = suggestions;
    }

    public String getOriginalTerm() {
        return originalTerm;
    }

    public List<String> getSuggestions() {
        return suggestions;
    }
}
